server:
  host: "127.0.0.1"
  port: 8080
  # tls:
  #   endpoint-identification-algorithm: "NONE"
  #   # client-auth: "REQUIRED"
  #   trust:
  #     keystore:
  #       passphrase: "changeit"
  #       trust-store: true
  #       resource:
  #         resource-path: "server.p12"
  #   private-key:
  #     keystore:
  #       passphrase: "changeit"
  #       resource:
  #         resource-path: "server.p12"
